server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: verification-service

  web:
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/dev}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:localhost:*}
  clients:
    encrypt-service-url: ${ENCRYPT_SERVICE_URL}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}

  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}