name: Deploy Spring Boot API

env:
  DB_URL: ${{ secrets.DB_URL }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
  MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
  MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
  SWAGGER_ENABLED: ${{secrets.SWAGGER_ENABLED}}
  ENCRYPT_SERVICE_URL: ${{secrets.ENCRYPT_SERVICE_URL}}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Puedes usar 'zulu' o 'adopt' si prefieres otra distribución
          java-version: '21'

      - name: Check Java version
        run: java -version

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew build # o mvn package si usas Maven

      - name: Rename JAR
        run: |
          mkdir -p build/libs/final
          JAR_FILE=$(ls build/libs/*.jar | grep -v plain | head -n 1)
          cp "$JAR_FILE" build/libs/final/app.jar

      - name: Copy JAR to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: build/libs/final/app.jar
          target: /opt/spring-auth-api/

      - name: Restart Spring Boot service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: DB_URL,DB_USER,DB_PASSWORD,CORS_ALLOWED_ORIGINS,MAIL_USERNAME,MAIL_PASSWORD,ENCRYPT_SERVICE_URL
          script: |
            cat <<EOF > /opt/spring-auth-api/.env
            DB_URL=$DB_URL
            DB_USER=$DB_USER
            DB_PASSWORD=$DB_PASSWORD
            CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGIN
            MAIL_USERNAME=$MAIL_USERNAME
            MAIL_PASSWORD=$MAIL_PASSWORD
            ENCRYPT_SERVICE_URL=$ENCRYPT_SERVICE_URL
            EOF
            chmod 600 /opt/spring-auth-api/.env
            sudo systemctl daemon-reload
            sudo systemctl restart spring-auth-api.service
